# syntax=docker/dockerfile:1@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

# renovate: datasource=docker depName=h7d7l6t4/devcontainer/ubuntu-base
ARG BASE_VERSION=noble

FROM public.ecr.aws/h7d7l6t4/devcontainer/ubuntu-base:${BASE_VERSION:-latest}

# [Optional] Uncomment this section to install additional OS packages.
# RUN $(which sudo) apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && $(which sudo) apt-get install -y --no-install-recommends <your-package-list-here>
