# syntax=docker/dockerfile:1@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

# renovate: datasource=docker depName=h7d7l6t4/devcontainer/ubuntu-base
ARG BASE_VERSION=noble@sha256:6b82d47ee79bb0d79f921bf50f08213e3d3f0be004b5d32061bffb72b92043f8

FROM public.ecr.aws/h7d7l6t4/devcontainer/ubuntu-base:${BASE_VERSION:-latest}

# [Optional] Uncomment this section to install additional OS packages.
# RUN $(which sudo) apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && $(which sudo) apt-get install -y --no-install-recommends <your-package-list-here>
